### ISSUE TITLE
Bottom Banner comes up abit.

### ISSUE THREAD

**Issue by jsobers1331** [CanRau/MarkupCookieConsent#1]
Hi, 

Thanks for the great Module.

Just letting you know that in your css file

```
form {
    margin-bottom: 20px;
}
```

is pushing the bottom banner up abit.

When I remove it, it looks better.

**Comment by CanRau** [comment]
Sorry but I can't find it right now.. Where is that piece of css coming from?

**Comment by jsobers1331** [comment]
Sorry, it was my mistake. I found the CSS in one of my existing CSS files and corrected it.

Thanks for the module.

**Comment by CanRau** [comment]
Great you could fix it :)

Strangely I had the same issue couple of weeks ago^^
