### ISSUE TITLE
Processwire >= 3.0.0 required?

### ISSUE THREAD

**Issue by jonashamm** [CanRau/MarkupCookieConsent#2]
Hey there! Thank you for your helpful module!
I had on issue. I run a processwire 2.7.2 installation. If I understand it correctly, the master-branch is meant for processwire 2.* ? But in MarkupCookieConsent.module it says "'requires' => 'ProcessWire>=3.0.0"... So I only could install the plugin when I changed this line to 'requires' => 'ProcessWire>=2.7.2.

I also had an issue with the languages of the message. (no problem now, because my website is uni-lingual). But maybe this is due to my wrong understanding of which version of processwire this is meant for?

**Comment by CanRau** [comment]
i guess the first one is my fault..forgot this line in the commit

don't get the second...what kind of issue you had with the messages?

**Comment by jonashamm** [comment]
I am running a page in german. Anytime I typed something into the translation fields for the message shown by the plugin and for the accept button, it wasn't saved. When I clicked "Save", they disappeared.

In the frontend, no text showed up, not even the original message, only an empty bar and an empty bottom of the cookie warning. Maybe this has to do something with some custom configurations of my processwire installation... but if not, I thought, you should know about :)

**Comment by CanRau** [comment]
so you have languagesupport installed or german is the only language?
just installed 2.7.2 and current markupCookieConsent master and everything works just fine
![bildschirmfoto 2017-04-28 um 22 12 54](https://cloud.githubusercontent.com/assets/5196971/25552456/e65c971a-2c5f-11e7-9369-8435dcd2dcc1.png)

or what do you mean?

**Comment by jonashamm** [comment]
Yes I have languagesupport installed. I will make a screenshot of my configs later this week and post it here.
