### ISSUE TITLE
Translations not saved

### ISSUE THREAD

**Issue by jonashamm** [CanRau/MarkupCookieConsent#3]
Hi, I think for later reference it's better if I open a new issue for what we discussed in #2 

So here's the issue: I use multiple languages in the project but the only language currently used in the frontend is german. I type some german text into the translation-fields:
![german1](https://cloud.githubusercontent.com/assets/1230322/25709971/203d4ed6-30eb-11e7-85c9-091710f98c40.png)

Then I click submit at the bottom. But the translation field contents aren't saved, they are empty now. The cookiebar at the bottom is visible, but without any texts:
![german2](https://cloud.githubusercontent.com/assets/1230322/25709975/24c88e34-30eb-11e7-92cb-299a6c9488ae.png)

**Comment by CanRau** [comment]
I used some PW api to code this language functionality which weren't working at that time
(quite sure I developed this module for pw3, but might be wrong)
https://github.com/ryancramerdesign/ProcessWire/commit/2fe134b7b059fff023f0f37c7f172a9853c88af2 this patch by Ryan fixed this...
so you either upgrade to 2.8 (which should work, I haven't tried it) or 3.x
or try to apply this patch on your own..could work..but depends on the entire codebase, so could more fixes could be needed

I'm adding a note to the readme, closing this issue now
feel free to reopen or start another one if needed ;-)
